# Your Solution
version: '3'
services:
  book_catalog:
    image: book_catalog:v1
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://sit722_postgresql_arun_user:8Xj1VmCY4OYjvB5bdEyuT1dTO87d3rfa@dpg-crp5f82j1k6c73c081g0-a.oregon-postgres.render.com/sit722_postgresql_arun
  inventory_management:
    image: inventory_management:v1
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://sit722_postgresql_arun_user:8Xj1VmCY4OYjvB5bdEyuT1dTO87d3rfa@dpg-crp5f82j1k6c73c081g0-a.oregon-postgres.render.com/sit722_postgresql_arun