# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: sit7222part3.azurecr.io/book_catalog:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DATABASE_URL
          value: "postgresql://sit722_postgresql_arun_user:8Xj1VmCY4OYjvB5bdEyuT1dTO87d3rfa@dpg-crp5f82j1k6c73c081g0-a.oregon-postgres.render.com/sit722_postgresql_arun"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - port: 7000
      targetPort: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: sit7222part3.azurecr.io/inventory_management:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7001
        env:
        - name: PORT
          value: "7001"
        - name: DATABASE_URL
          value: "postgresql://sit722_postgresql_arun_user:8Xj1VmCY4OYjvB5bdEyuT1dTO87d3rfa@dpg-crp5f82j1k6c73c081g0-a.oregon-postgres.render.com/sit722_postgresql_arun"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - port: 7001
      targetPort: 7001